<a href="https://colab.research.google.com/github/Aadi1039/Data-Science-with-Python/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array1d)

array2d = np.array([[10, 20, 30], [40, 50, 60]])
print("\n2D Array:\n", array2d)

zeros_array = np.zeros((3, 4))
print("\nZeros Array (3x4):\n", zeros_array)

ones_array = np.ones((2, 3))
print("\nOnes Array (2x3):\n", ones_array)

range_array = np.arange(0, 10, 2)
print("\nRange Array (0 to 10, step 2):", range_array)

linspace_array = np.linspace(0, 1, 5)
print("\nLinspace Array (5 points between 0 and 1):", linspace_array)

1D Array: [1 2 3 4 5]

2D Array:
 [[10 20 30]
 [40 50 60]]

Zeros Array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

Range Array (0 to 10, step 2): [0 2 4 6 8]

Linspace Array (5 points between 0 and 1): [0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np

array = np.arange(5,50,5)
print(array)

[ 5 10 15 20 25 30 35 40 45]


### Basic Array Arithmetic

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)

print("Subtraction:", a - b)

print("Element-wise Multiplication:", a * b)

print("Element-wise Division:", a / b)

print("Scalar Multiplication:", a * 3)

print("Dot Product:", np.dot(a, b))

print("Dot Product with @:", a @ b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]
Scalar Multiplication: [3 6 9]
Dot Product: 32
Dot Product with @: 32


### Universal Functions (ufuncs)

In [ ]:
import numpy as np

array = np.array([-1, 0, 1, 2, 3.5])

print("Absolute values:", np.abs(array))

print("Square roots:", np.sqrt(array[array >= 0]))

print("Exponentials:", np.exp(array))

print("Natural Logarithms:", np.log(array[array > 0]))

print("Sine values:", np.sin(array))

print("Cosine values:", np.cos(array))

print("Sum of array elements:", np.sum(array))

print("Mean of array elements:", np.mean(array))

print("Maximum element:", np.max(array))

print("Minimum element:", np.min(array))

Absolute values: [1.  0.  1.  2.  3.5]
Square roots: [0.         1.         1.41421356 1.87082869]
Exponentials: [ 0.36787944  1.          2.71828183  7.3890561  33.11545196]
Natural Logarithms: [0.         0.69314718 1.25276297]
Sine values: [-0.84147098  0.          0.84147098  0.90929743 -0.35078323]
Cosine values: [ 0.54030231  1.          0.54030231 -0.41614684 -0.93645669]
Sum of array elements: 5.5
Mean of array elements: 1.1
Maximum element: 3.5
Minimum element: -1.0


In [ ]:
import numpy as np

py_list = [10, 20, 30, 40, 50]
py_array = np.array(py_list)

print(" List:", py_list)
print(" Array:", py_array)
print("Array:", type(py_array))

 List: [10, 20, 30, 40, 50]
 Array: [10 20 30 40 50]
Array: <class 'numpy.ndarray'>


Original List: [10, 20, 30, 40, 50]
Type of Original List: <class 'list'>

Converted Tuple: (10, 20, 30, 40, 50)
Type of Converted Tuple: <class 'tuple'>


In [ ]:
import numpy as np

py_tuple = (10, 20, 30, 40, 50)
numpy_array_from_tuple = np.array(py_tuple)

print("Original Python Tuple:", py_tuple)
print("Converted NumPy Array:", numpy_array_from_tuple)
print("Type of NumPy Array:", type(numpy_array_from_tuple))

Original Python Tuple: (10, 20, 30, 40, 50)
Converted NumPy Array: [10 20 30 40 50]
Type of NumPy Array: <class 'numpy.ndarray'>


In [ ]:
import numpy as np
A= np.ones((4,5),dtype=np.int16)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np
A= np.full((4,5), fill_value=7, dtype=np.int16)
print(A)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
import numpy as np
A= np.ones((4,5),dtype=np.int16)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np
A= np.random.rand(3,2)
print(A)

[[0.21248392 0.5249582 ]
 [0.10410138 0.73436029]
 [0.53991218 0.58133481]]


In [ ]:
import numpy as np

array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d)

array1d = array2d.flatten()
print( array1d)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr= np.array([0,1,2,3,4,5,6,7,8,9,10])
print("arr[3:6]=",arr[3:6])
print("arr[1::2]=",arr[1::2])


arr[3:6]= [3 4 5]
arr[1::2]= [1 3 5 7 9]


In [ ]:
import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
print("APPEND ARRAYS:\n")
arr3=np.append(arr1,arr2)
print(arr3)

APPEND ARRAYS:

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
arr1= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2= np.array([[6,7,8],[9,10,11],[12,13,14]])
print("APPEND ARRAYS:\n")
arr3=np.append(arr1,arr2,axis=0)
print(arr3)

APPEND ARRAYS:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
import numpy as np
arr = np.arange(16).reshape((4,4))
print("2 D arrayb is:\n",arr)
left,right=np.split(arr,[2],axis=1)
print("Left array is:\n",left)
print("Right array is:\n",right)

2 D arrayb is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Left array is:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right array is:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
